version: 2

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
